services:
  - type: web
    name: linux-vps
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: WEB_USER
        value: admin
      - key: WEB_PASS
        generateValue: true
    healthCheckPath: /
