services:
  - type: web
    name: linux-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "6969"
      - key: SSH_PASSWORD
        value: "2003"
