services:
  - type: web
    name: linux-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "6969"
      - key: BORE_PORT
        value: "48251"
